services:
  - type: web
    name: busca-cep
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SCRAPER_DELAY_MS
        value: 2000
      - key: MAX_REQUESTS_PER_MINUTE
        value: 30
      - key: DISABLE_CRON
        value: false
      - key: DISABLE_BACKUP
        value: false
      - key: DISABLE_FILE_LOGS
        value: false
      - key: CRON_SECRET
        generateValue: true
      - key: MANUAL_EXECUTION_TOKEN
        generateValue: true
      - key: UPDATE_SCHEDULE
        value: "0 2 * * 1"
      - key: COLLECT_SCHEDULE
        value: "0 6 * * *"

  - type: pserv
    name: busca-cep-db
    env: postgresql
    plan: free
    databaseName: busca_cep
    databaseUser: busca_cep_user
